name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  release-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install tools via asdf
        uses: asdf-vm/actions/install@v3.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor  }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
